// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'but': string;
  'but_area': string;
  'content': string;
  'input_area': string;
}
export const cssExports: CssExports;
export default cssExports;
