// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'comment_area': string;
  'content': string;
  'date_text': string;
  'nickname_text': string;
  'text_area': string;
}
export const cssExports: CssExports;
export default cssExports;
