// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'emoji': string;
  'file': string;
  'pic': string;
  'tool_icon': string;
}
export const cssExports: CssExports;
export default cssExports;
