// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'list_block': string;
  'scroll_bar_block': string;
  'scroll_thumb': string;
  'shadow_bottom': string;
  'shadow_top': string;
  'shadow_vertical': string;
  'wrapper_content': string;
}
export const cssExports: CssExports;
export default cssExports;
