// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom_border': string;
  'content': string;
  'date_area': string;
  'desc': string;
  'ellipsis': string;
  'icon': string;
  'info_area': string;
  'nickname': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
