// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'list': string;
  'list_area': string;
  'load_more': string;
  'scroll_bar_thumb': string;
  'scroll_bar_track': string;
  'shadow_bottom': string;
  'shadow_top': string;
  'shadow_vertical': string;
}
export const cssExports: CssExports;
export default cssExports;
