// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'emoji': string;
  'emoji_item': string;
  'emoji_wrapper': string;
  'tool_icon': string;
}
export const cssExports: CssExports;
export default cssExports;
