// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'arrow_left': string;
  'arrow_right': string;
  'img_content': string;
  'text_content': string;
}
export const cssExports: CssExports;
export default cssExports;
