// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'scroll_bar_thumb': string;
  'scroll_bar_track': string;
}
export const cssExports: CssExports;
export default cssExports;
