// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ali-cen': string;
  'flex': string;
  'flex-1': string;
  'jus-cen': string;
}
export const cssExports: CssExports;
export default cssExports;
