// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'content': string;
  'desc_area': string;
  'nickname': string;
  'sologan': string;
}
export const cssExports: CssExports;
export default cssExports;
